openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/:
    get:
      operationId: listPosts
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        author:
                          type: string
                          readOnly: true
                        title:
                          type: string
                          maxLength: 128
                        body:
                          type: string
                      required:
                      - title
                      - body
          description: ''
    post:
      operationId: CreatePost
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  maxLength: 128
                body:
                  type: string
              required:
              - title
              - body
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                  title:
                    type: string
                    maxLength: 128
                  body:
                    type: string
                required:
                - title
                - body
          description: ''
  /api/v1/search/:
    get:
      operationId: listPosts
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        author:
                          type: string
                          readOnly: true
                        title:
                          type: string
                          maxLength: 128
                        body:
                          type: string
                      required:
                      - title
                      - body
          description: ''
  /api/v1/users/:
    get:
      operationId: listUsers
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        username:
                          type: string
                          description: Required. 150 characters or fewer. Letters,
                            digits and @/./+/-/_ only.
                          pattern: ^[\w.@+-]+$
                          maxLength: 150
                        email:
                          type: string
                          format: email
                          maxLength: 254
                        first_name:
                          type: string
                          maxLength: 30
                        last_name:
                          type: string
                          maxLength: 150
                      required:
                      - username
          description: ''
  /api/v1/users/{id}/:
    get:
      operationId: RetrieveUser
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  username:
                    type: string
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                    pattern: ^[\w.@+-]+$
                    maxLength: 150
                  email:
                    type: string
                    format: email
                    maxLength: 254
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
                required:
                - username
          description: ''
  /api/v1/users/{id}/posts/:
    get:
      operationId: listPosts
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        author:
                          type: string
                          readOnly: true
                        title:
                          type: string
                          maxLength: 128
                        body:
                          type: string
                      required:
                      - title
                      - body
          description: ''
    post:
      operationId: CreatePost
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  maxLength: 128
                body:
                  type: string
              required:
              - title
              - body
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                  title:
                    type: string
                    maxLength: 128
                  body:
                    type: string
                required:
                - title
                - body
          description: ''
  /api/v1/posts/{id}/:
    get:
      operationId: RetrievePost
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                  title:
                    type: string
                    maxLength: 128
                  body:
                    type: string
                required:
                - title
                - body
          description: ''
    put:
      operationId: UpdatePost
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  maxLength: 128
                body:
                  type: string
              required:
              - title
              - body
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                  title:
                    type: string
                    maxLength: 128
                  body:
                    type: string
                required:
                - title
                - body
          description: ''
    patch:
      operationId: PartialUpdatePost
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  maxLength: 128
                body:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                  title:
                    type: string
                    maxLength: 128
                  body:
                    type: string
                required:
                - title
                - body
          description: ''
    delete:
      operationId: DestroyPost
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /api/v1/posts/{id}/comments/:
    get:
      operationId: listComments
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                  previous:
                    type: string
                    nullable: true
                  results:
                    type: array
                    items:
                      properties:
                        id:
                          type: integer
                          readOnly: true
                        body:
                          type: string
                          maxLength: 256
                        post:
                          type: string
                          readOnly: true
                        author:
                          type: string
                          readOnly: true
                      required:
                      - body
          description: ''
    post:
      operationId: CreateComment
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                body:
                  type: string
                  maxLength: 256
              required:
              - body
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  body:
                    type: string
                    maxLength: 256
                  post:
                    type: string
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                required:
                - body
          description: ''
  /api/v1/posts/comments/{id}/:
    get:
      operationId: RetrieveComment
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  body:
                    type: string
                    maxLength: 256
                  post:
                    type: string
                    readOnly: true
                  author:
                    type: string
                    readOnly: true
                required:
                - body
          description: ''
    delete:
      operationId: DestroyComment
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /api/v1/register/:
    post:
      operationId: CreateUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+$
                  maxLength: 150
                email:
                  type: string
                  format: email
                  maxLength: 254
                password:
                  type: string
                  writeOnly: true
                first_name:
                  type: string
                  maxLength: 30
                last_name:
                  type: string
                  maxLength: 150
              required:
              - username
              - password
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    readOnly: true
                  username:
                    type: string
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                    pattern: ^[\w.@+-]+$
                    maxLength: 150
                  email:
                    type: string
                    format: email
                    maxLength: 254
                  first_name:
                    type: string
                    maxLength: 30
                  last_name:
                    type: string
                    maxLength: 150
                required:
                - username
          description: ''
  /api/v1/login/:
    post:
      operationId: CreateObtainAuthToken
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
